export interface RouteConfig {
  path: string;
  dynamicPath?: RegExp;
  component: string;
  protected: boolean;
  layout: boolean;
}

export const routeConfig: Record<string, RouteConfig> = {
  home: {
    path: '/home',
    component: 'HomePage',
    protected: true,
    layout: true,
  },
  dashboard: {
    path: '/dashboard',
    component: 'Dashboard',
    protected: true,
    layout: true,
  },
  usuarios: {
    path: '/gestaodeusuarios',
    component: 'UserTeamRoleManagement',
    protected: true,
    layout: true,
  },
  'usuarios-novo': {
    path: '/gestaodeusuarios/usuarios/novo',
    component: 'UserFormPage',
    protected: true,
    layout: true,
  },
  'usuarios-editar': {
    path: '/gestaodeusuarios/usuarios/editar/:id',
    dynamicPath: /^\/gestaodeusuarios\/usuarios\/editar\/[^/]+$/,
    component: 'UserFormPage',
    protected: true,
    layout: true,
  },
  'times-novo': {
    path: '/gestaodeusuarios/times/novo',
    component: 'TeamFormPage',
    protected: true,
    layout: true,
  },
  'times-editar': {
    path: '/gestaodeusuarios/times/editar/:id',
    dynamicPath: /^\/gestaodeusuarios\/times\/editar\/[^/]+$/,
    component: 'TeamFormPage',
    protected: true,
    layout: true,
  },
  'perfis-novo': {
    path: '/gestaodeusuarios/perfis/novo',
    component: 'RoleFormPage',
    protected: true,
    layout: true,
  },
  'perfis-editar': {
    path: '/gestaodeusuarios/perfis/editar/:id',
    dynamicPath: /^\/gestaodeusuarios\/perfis\/editar\/[^/]+$/,
    component: 'RoleFormPage',
    protected: true,
    layout: true,
  },
  documentos: {
    path: '/documentos',
    component: 'DocumentsPage',
    protected: true,
    layout: true,
  },
  'documentos-carregar': {
    path: '/documentos/carregar',
    component: 'DocumentUploadPage',
    protected: true,
    layout: true,
  },
  'documentos-analisar': {
    path: '/documentos/:documentId/analisar',
    dynamicPath: /^\/documentos\/[^/]+\/analisar$/,
    component: 'DocumentAnalysisPage',
    protected: true,
    layout: false,
  },
  extraction: {
    path: '/documentos/:documentId/extrair',
    dynamicPath: /^\/documentos\/[^/]+\/extrair$/,
    component: 'DocumentExtractionPage',
    protected: true,
    layout: true,
  },
  tipos: {
    path: '/tipos',
    component: 'DocumentTypesPage',
    protected: true,
    layout: true,
  },
  perguntas: {
    path: '/perguntas',
    component: 'QuestionsPage',
    protected: true,
    layout: true,
  },
  questionarios: {
    path: '/questionarios',
    component: 'QuestionnairesPage',
    protected: true,
    layout: true,
  },
  'questionarios-new': {
    path: '/questionarios/new',
    component: 'QuestionnaireEditPage',
    protected: true,
    layout: true,
  },
  'questionarios-edit': {
    path: '/questionarios/:id',
    dynamicPath: /^\/questionarios\/[^/]+$/,
    component: 'QuestionnaireEditPage',
    protected: true,
    layout: true,
  },
  styleguide: {
    path: '/styleguide',
    component: 'StyleGuidePage',
    protected: true,
    layout: true,
  },
  tarefas: {
    path: '/tarefas',
    component: 'TarefasPage',
    protected: true,
    layout: true,
  },
  workflow: {
    path: '/workflow',
    component: 'DocumentWorkflowPage',
    protected: true,
    layout: true,
  },
  'documentos-workflow': {
    path: '/documentos/workflow',
    component: 'DocumentWorkflowPage',
    protected: true,
    layout: true,
  },
  'workflow-bulk-atribuir': {
    path: '/documentos/workflow/atribuir',
    component: 'WorkflowBulkAtribuirPage',
    protected: true,
    layout: true,
  },
  'workflow-bulk-reprovar': {
    path: '/documentos/workflow/reprovar',
    component: 'WorkflowBulkReprovarPage',
    protected: true,
    layout: true,
  },
  'workflow-criar': {
    path: '/workflow/criar',
    component: 'WorkflowCreatePage',
    protected: true,
    layout: true,
  },
  'documentos-workflow-criar': {
    path: '/documentos/workflow/criar',
    component: 'WorkflowCreatePage',
    protected: true,
    layout: true,
  },
  'workflow-editor': {
    path: '/workflow/editor',
    component: 'WorkflowEditorPage',
    protected: true,
    layout: true,
  },
  'documentos-workflow-editor': {
    path: '/documentos/workflow/editor',
    component: 'WorkflowEditorPage',
    protected: true,
    layout: true,
  },
  'workflow-gerenciar': {
    path: '/workflow/gerenciar',
    component: 'WorkflowManagementPage',
    protected: true,
    layout: true,
  },
  'documentos-workflow-gerenciar': {
    path: '/documentos/workflow/gerenciar',
    component: 'WorkflowManagementPage',
    protected: true,
    layout: true,
  },
  prompts: {
    path: '/prompts',
    component: 'PromptsListPage',
    protected: true,
    layout: true,
  },
  'prompts-importar': {
    path: '/prompts/importar',
    component: 'PromptsImportPage',
    protected: true,
    layout: true,
  },
  'prompts-novo': {
    path: '/prompts/novo',
    component: 'PromptEditPage',
    protected: true,
    layout: true,
  },
  'prompts-editar': {
    path: '/prompts/edit/:id',
    dynamicPath: /^\/prompts\/edit\/[^/]+$/,
    component: 'PromptEditPage',
    protected: true,
    layout: true,
  },
  ferramentas: {
    path: '/ferramentas',
    component: 'FerramentasManagementPage',
    protected: true,
    layout: true,
  },
  'ferramentas-novo': {
    path: '/ferramentas/novo',
    component: 'FerramentasCreatePage',
    protected: true,
    layout: true,
  },
  'workflow-gestao': {
    path: '/workflow/gestao',
    component: 'WorkflowGestaoPage',
    protected: true,
    layout: true,
  },
  'documentos-workflow-gestao': {
    path: '/documentos/workflow/gestao',
    component: 'WorkflowGestaoPage',
    protected: true,
    layout: true,
  },
  'workflow-gestao-novo': {
    path: '/workflow/gestao/novo',
    component: 'WorkflowFormPage',
    protected: true,
    layout: true,
  },
  'documentos-workflow-gestao-novo': {
    path: '/documentos/workflow/gestao/novo',
    component: 'WorkflowFormPage',
    protected: true,
    layout: true,
  },
  'workflow-gestao-editar': {
    path: '/workflow/gestao/editar/:id',
    dynamicPath: /^\/workflow\/gestao\/editar\/[^/]+$/,
    component: 'WorkflowFormPage',
    protected: true,
    layout: true,
  },
  'documentos-workflow-gestao-editar': {
    path: '/documentos/workflow/gestao/editar/:id',
    dynamicPath: /^\/documentos\/workflow\/gestao\/editar\/[^/]+$/,
    component: 'WorkflowFormPage',
    protected: true,
    layout: true,
  },
  'workflow-versoes': {
    path: '/documentos/workflows/:id/versoes',
    dynamicPath: /^\/documentos\/workflows\/[^/]+\/versoes$/,
    component: 'WorkflowVersionHistoryPage',
    protected: true,
    layout: true,
  },
  'workflow-versoes-nova': {
    path: '/documentos/workflows/:id/versoes/nova',
    dynamicPath: /^\/documentos\/workflows\/[^/]+\/versoes\/nova$/,
    component: 'WorkflowVersionCreatePage',
    protected: true,
    layout: true,
  },
  'workflow-versoes-detalhe': {
    path: '/documentos/workflows/:id/versoes/:versionId',
    dynamicPath: /^\/documentos\/workflows\/[^/]+\/versoes\/[^/]+$/,
    component: 'WorkflowVersionDetailPage',
    protected: true,
    layout: true,
  },
  'workflow-versoes-comparar': {
    path: '/documentos/workflows/:id/versoes/comparar',
    dynamicPath: /^\/documentos\/workflows\/[^/]+\/versoes\/comparar$/,
    component: 'WorkflowVersionComparePage',
    protected: true,
    layout: true,
  },
  'workflow-versionamento-ajuda': {
    path: '/documentos/workflows/versionamento/ajuda',
    component: 'WorkflowVersioningHelpPage',
    protected: true,
    layout: true,
  },
  'api-templates': {
    path: '/templates/api',
    component: 'APITemplatesPage',
    protected: true,
    layout: true,
  },
  'api-templates-novo': {
    path: '/templates/api/novo',
    component: 'APITemplateFormPage',
    protected: true,
    layout: true,
  },
  'api-templates-editar': {
    path: '/templates/api/editar/:id',
    dynamicPath: /^\/templates\/api\/editar\/[^/]+$/,
    component: 'APITemplateFormPage',
    protected: true,
    layout: true,
  },
  auditoria: {
    path: '/auditoria',
    component: 'AuditPage',
    protected: true,
    layout: true,
  },
  comparador: {
    path: '/documentos/comparador',
    component: 'ComparadorPage',
    protected: true,
    layout: true,
  },
  'comparador-analise': {
    path: '/documentos/comparador/analise',
    component: 'ComparadorAnalysisPage',
    protected: true,
    layout: true,
  },
};

export const legacyRoutes = [
  { from: '/documentos/tipos', to: '/tipos' },
  { from: '/documentos/perguntas', to: '/perguntas' },
  { from: '/documentos/questionarios', to: '/questionarios' },
];